spring:
  application:
    name: uaifood-payment-service
  datasource:
    url: jdbc:postgresql://localhost:5433/uaifood_payment
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  rabbitmq:
    host: localhost
    port: 5673
    username: guest
    password: guest
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27018/uaifood_payment?authSource=admin

server:
  port: 8082

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

payment:
  mock:
    enabled: true
    success-rate: 0.8  # 80% success rate for mock payments 